apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kserve-ns-model-cache.populateConfigMapName" . }}
  labels:
    {{- include "kserve-ns-model-cache.labels" . | nindent 4 }}
data:
  populate_hf.py: |
{{ .Files.Get "scripts/populate_hf.py" | indent 4 }}
